# Generated by Django 5.1.2 on 2025-11-29 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echochatapp', '0003_chatgroup_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='echochatapp.chatgroup'),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
