# Generated by Django 5.2.8 on 2025-12-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echochatapp', '0006_privatechatrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateChatRequest',
        ),
    ]
