# Generated by Django 5.2.8 on 2025-12-02 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echochatapp', '0008_privatechatrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateChatRequest',
        ),
    ]
