# Generated by Django 5.2.8 on 2025-12-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echochatapp', '0009_delete_privatechatrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=150)),
                ('receiver_name', models.CharField(max_length=150)),
                ('chat_request', models.CharField(max_length=10)),
            ],
        ),
    ]
